#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/mywebsite
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.datasource.username=joe
#spring.datasource.password=000000
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#org.hibernate.dialect.Dialect=org.hibernate.dialect.MySQL8Dialect
#server.servlet.context-path=/mywebsite
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: joe
    password: "000000"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mywebsite
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static
      cache:
        period: 0
server:
  servlet:
    context-path: /mywebsite
