spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:h2:${DB_URL}
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static
      cache:
        period: 0
server:
  servlet:
    context-path: /myfinances
